### ISSUE TITLE
Test suite hangs with ghc 8.4 (apparently due to hspec-2.5.0)

### ISSUE THREAD

**Issue by DanBurton** [jcristovao/enclosed-exceptions#12]
The last thing printed is:

```
Control.Exception.Enclosed
  catchAny
    catches exceptions thrown from the inside
    doesn't catch exceptions thrown from the outside
    doesn't catch exceptions lazily thrown in its pure result
  catchDeep
    catches exceptions thrown from the inside
    catches exceptions thrown from the outside
    catches exceptions lazily thrown in its pure result
  tryAny
    catches exceptions thrown from the inside
    doesn't catch exceptions thrown from the outside
    doesn't catch exceptions lazily thrown in its pure result
```

The next test is:

https://github.com/jcristovao/enclosed-exceptions/blob/ba1b3567f37e1a6e1fbc6c4069abc0030ff7b89e/test/main.hs#L85

which suggests to me that something is going on with the "blocked indefinitely" behavior. Possibly a GHC regression?

**Comment by snoyberg** [comment]
I don't have much time to look at this right now, but a quick test on my machine did not reproduce this. I was using nightly-2018-03-14.

**Comment by DanBurton** [comment]
@snoyberg that was a fortunate observation. I too am able to reproduce a passing test suite with nightly-2018-03-14. However, I am also able to reproduce the error with nightly-2018-03-17. This helps us isolate the cause, which is apparently `hspec-2.5.0`.

```bash
stack unpack enclosed-exceptions-1.0.2 && cd enclosed-exceptions-1.0.2
edit stack.yaml # try the various stack.yaml files
stack test
```

```yaml
# stack.yaml
# requires stack upgrade --git
# test suite passes
resolver: nightly-2018-03-14
```

```yaml
# stack.yaml
# requires stack upgrade --git
# test suite hangs
resolver: nightly-2018-03-14
extra-deps:
- hspec-2.5.0
- hspec-core-2.5.0
- hspec-discover-2.5.0
```

```yaml
# stack.yaml
# test suite hangs
resolver: nightly-2018-03-17
```

```yaml
# stack.yaml
# test suite passes
resolver: nightly-2018-03-17
extra-deps:
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
```

(For those who don't want to bother with `stack upgrade --git`, you can simply refer to the last 2 examples, which are sufficient to illustrate that `hspec-2.5.0` is the cause of the discrepancy here.)
